
create table apunte_alumno (
    fecha_subida timestamp(6) not null,
    id bigint generated by default as identity,
    username varchar(20) not null,
    asignatura_id varchar(100),
    tema varchar(250) not null,
    contenido_original oid not null,
    primary key (id)
);

create table asignatura (
    sensibilidad integer,
    asignatura_id varchar(100) not null,
    color_tema oid,
    system_prompt oid,
    temas oid,
    titulo oid,
    primary key (asignatura_id)
);

create table aviso_estancamiento (
    iteraciones integer not null,
    ambito varchar(6) not null check (ambito in ('CHAT','RETO')),
    fecha_actualizacion timestamp(6),
    fecha_creacion timestamp(6) not null,
    fecha_resuelto timestamp(6),
    id bigint generated by default as identity,
    estado varchar(10) not null check (estado in ('ABIERTO','RESUELTO')),
    username varchar(20) not null,
    asignatura_id varchar(100),
    tema varchar(250),
    pregunta_ejemplo oid,
    primary key (id)
);

create table ejercicio (
    publicado boolean not null,
    fecha_creacion timestamp(6) not null,
    id bigint generated by default as identity,
    origen varchar(12) not null check (origen in ('PROPIO','GENERADO_IA','PROPUESTO')),
    autor_username varchar(20),
    dificultad varchar(20),
    lenguaje varchar(20),
    asignatura_id varchar(100),
    tema varchar(200),
    titulo varchar(200) not null,
    enunciado oid not null,
    primary key (id)
);

create table estado_microhito (
    independencia_hito integer,
    orden integer not null,
    fecha_completado timestamp(6),
    id bigint generated by default as identity,
    microhito_id bigint not null,
    resolucion_id bigint not null,
    estado varchar(12) not null check (estado in ('PENDIENTE','EN_PROGRESO','COMPLETADO')),
    titulo varchar(200) not null,
    primary key (id)
);

create table microhito (
    orden integer not null,
    ejercicio_id bigint not null,
    id bigint generated by default as identity,
    titulo varchar(200) not null,
    criterio_validacion oid,
    descripcion oid,
    primary key (id)
);

create table perfil_alumno_registro (
    contador_practico integer not null,
    contador_teorico integer not null,
    esperando_recalibracion boolean not null,
    iteracion_chat integer not null,
    id bigint generated by default as identity,
    username varchar(20) not null,
    asignatura_id varchar(100),
    primary key (id)
);

create table registro_consulta (
    iteracion integer,
    valoracion integer,
    fecha_hora timestamp(6) not null,
    id bigint generated by default as identity,
    tipo varchar(10) not null check (tipo in ('CHAT','EJERCICIO')),
    fase varchar(15),
    username varchar(20) not null,
    asignatura_id varchar(100),
    tema varchar(200),
    comentario_valoracion oid,
    pregunta oid not null,
    respuesta oid,
    primary key (id)
);

create table registro_resolucion (
    n_mensajes_alumno integer not null,
    n_pistas_reveladoras integer not null,
    n_recargas integer not null,
    porcentaje_independencia integer,
    tiempo_total_segundos integer,
    ejercicio_id bigint not null,
    fecha_fin timestamp(6),
    fecha_inicio timestamp(6),
    id bigint generated by default as identity,
    estado varchar(12) not null check (estado in ('EN_PROGRESO','COMPLETADO','ABANDONADO')),
    username varchar(20) not null,
    asignatura_id varchar(100),
    primary key (id)
);

alter table if exists estado_microhito
    add constraint fk_estado_microhito_resolucion foreign key (resolucion_id) references registro_resolucion;
alter table if exists microhito
    add constraint fk_microhito_ejercicio foreign key (ejercicio_id) references ejercicio;
